KickerIO/urls.py
from django.conf.urls import url, include
from django.views.decorators.csrf import csrf_exempt

print "MAIN URLS FILE"

urlpatterns = [
    url(r'^', include('apps.login_register.urls', namespace="login_register")),
    url(r'^news/', include('apps.news.urls', namespace="news")),
    url(r'^', include('django_alexa.urls')),
]

apps/login_register/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register/$', views.register, name="register"),
    url(r'^process_login/$', views.process_login, name="process_login"),
    url(r'^process_registration/$', views.process_registration, name="process_registration"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^account/(?P<id>\d+)$', views.account, name="account_settings"),
    url(r'^account/edit/(?P<id>\d+)$', views.edit, name="edit"),
    url(r'^account/update/(?P<id>\d+)$', views.update_account, name="update_account"),
    url(r'^follow/(?P<id>\d+)$', views.follow, name="follow"),
    url(r'^profile/(?P<id>\d+)$', views.profile, name="profile"),
    url(r'^search/$', views.search, name="search"),
]

apps/news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^get_new_articles/$', views.get_new_articles, name="get_new_articles"),
    url(r'^newsreel/$', views.newsreel, name="newsreel"),
    url(r'^share/(?P<id>\d+)$', views.share, name="share"),
    url(r'^like_article/(?P<id>\d+)$', views.like_article, name="like_article"),
    url(r'^unlike/(?P<id>\d+)$', views.unlike, name="unlike"),
]

apps/news/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
# IDEA: Look into url shorteners. Bit.ly?
class Article(models.Model):
    title = models.CharField(max_length=255)
    summarized_text = models.TextField()
    url = models.URLField()
    published_on = models.DateTimeField()
    main_image = models.URLField()
    creator = models.ForeignKey(User, related_name="creator", default=0)
    users = models.ManyToManyField(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Category(models.Model):
    name = models.CharField(max_length=45)
    articles = models.ManyToManyField(Article)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Like(models.Model):
    user = models.ForeignKey(User)
    article = models.ForeignKey(Article)
    created_at = models.DateTimeField(auto_now_add=True)

apps/news/forms.py
from django import forms

#Doesn't inherit from model, so using forms.Form instead of forms.ModelForm
class SummaryArticles(forms.Form):
    search_term = forms.CharField(max_length=45, required=True)

apps/news/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db.models import Q
import json

from .forms import SummaryArticles
from .models import Article, Category, Like
from ..login_register .models import User

from NLTK.getlinks import *

# Create your views here.
def index(request):
    print "*"*50
    print request.user.id
    print "*"*50
    form = SummaryArticles()
    profile = User.objects.get(id=request.user.id)
    context = {
        'profile': profile,
        'SummaryForm': form
    }
    return render(request, 'news/index.html', context)

def get_new_articles(request):
    if request.method == "POST":
        bound_form = SummaryArticles(request.POST)
        search_term = bound_form['search_term'].value()
        summary_dict = get_summarized_text(search_term)
        context = {
            'summary_dict': summary_dict
        }
        request.session['user_articles'] = summary_dict
    return redirect(reverse("news:index"))

def share(request, id):
    if request.method == "POST":
        shared = request.session['user_articles'][str(id)]
        user = User.objects.get(id=request.user.id)
        article = Article(
            title=shared['title'],
            summarized_text=" ".join(shared['summary_sentences']),
            url=shared['meta']['url'],
            published_on=shared['meta']['published_on'],
            main_image=shared['meta']['main_image'],
            creator_id=request.user.id
        )
        article.save()
        article.users.add(user)
        categories = " ".join(shared['meta']['site_categories'])
        category = Category(name=categories)
        category.save()
        category.articles.add(article)
    return redirect(reverse("news:newsreel"))

def newsreel(request):
    user_profile = User.objects.get(id=request.user.id).profile
    #get the user_id of everyone the logged in user is following
    network_ids = [am_following.user_id for am_following in user_profile.follows.all()]
    articles = Article.objects.filter(Q(creator__in=network_ids) | Q(creator=request.user.id))
    context = {
        'articles': articles
    }
    return render(request, 'news/newsreel.html', context)

def like_article(request, id):
    #NEED to validate that like doesn't already exist in the DB
    user = User.objects.get(id=request.user.id)
    article = Article.objects.get(id=id)
    like = Like.objects.create(
        user=user,
        article=article
    )
    article_likes = article.like_set.count()
    # return redirect(reverse("news:newsreel"))
    return HttpResponse(
        json.dumps(article_likes),
        content_type="application/json"
    )

def unlike(request, id):
    user = User.objects.get(id=request.user.id)
    article = Article.objects.get(id=id)
    like_obj = Like.objects.get(
        Q(user=user),
        Q(article=article)
    )
    like_obj.delete()
    article_likes = article.like_set.count()
    # return redirect(reverse("news:newsreel"))
    return HttpResponse(
        json.dumps(article_likes),
        content_type="application/json"
    )

apps/news/templates/news/index.html
{% extends 'login_register/layout.html' %}

{% block content %}
    <a class="btn-flat" href="{% url 'login_register:logout' %}">Logout</a>
    <a class="btn-flat" href="{% url 'login_register:account_settings' id=request.user.id %}">Account Settings</a>
    <a class="btn-flat" href="{% url 'news:newsreel' %}">Newsreel</a>
    <a class="btn-flat" href="{% url 'login_register:profile' id=request.user.id %}">Profile</a>
    <h2 class="newsreel">Your News</h2>
    <p class="red-text accent-3">Welcome, {{ request.user.first_name }}! <a id="help-link" href="">Need help?</a></p>
    <form action="{% url 'news:get_new_articles' %}" method="POST">
      {% csrf_token %}
      <div class="input-field">
        <label for="{{ SummaryForm.search_term.id_for_label }}">Search Term:</label>
        {{ SummaryForm.search_term }}
      </div>
      <input class="btn-flat scale-effect" type="submit" value="Submit">
    </form>
    {% for key, val in request.session.user_articles.iteritems %}
    <div class="card hoverable left col s12 m6 l4">
      <div class="card-image">
        <a href="{{ val.meta.url }}"><img class="responsive-img" src="{{ val.meta.main_image }}" /></a>
        <!-- <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">+</i></a> -->
      </div>
      <div class="card-content">
        <span class="card-title">{{ val.title }}</span>
        {% for sentence in val.summary_sentences %}
        <p>{{ sentence }}</p>
        {% endfor %}
      </div>
      <!-- <h4>Meta</h4>
      {% for x, y in val.meta.iteritems %}
        <p>{{y}}</p>
      {% endfor %} -->
      <form action="{% url 'news:share' id=key %}" method="POST">
        {% csrf_token %}
        <input class="btn-flat waves-effect waves-red" type="submit" value="Share">
      </form>
    </div>
    {% endfor %}

{% endblock %}

apps/news/templates/news/newsreel.html
{% extends 'login_register/layout.html' %}
{% load like_extras %}
{% load follow_extras %}
{% load static %}

{% block content %}
    <div class="row">
      <a class="left btn-flat waves-red" href="{% url 'news:index' %}">Home</a>
      <a class="btn-flat" href="{% url 'login_register:profile' id=request.user.id %}">Profile</a>
      <a class="btn-flat" href="{% url 'login_register:account_settings' id=request.user.id %}">Account Settings</a>
      <a class="btn-flat" href="{% url 'login_register:logout' %}">Logout</a>
      <form id="search_form" class="dropdown-button col s3 offset-s7 m3 offset-m7 l3 offset-l9" data-beloworigin="true" data-activates="dropdown1" action="{% url 'login_register:search' %}" method="POST">
        {% csrf_token %}
        <input type="search" name="find_friends" placeholder="Grow Your Network">
      </form>
      <ul id='dropdown1' class='dropdown-content col s12 m4 offset-m5 l4 offset-l6'></ul>
    </div>
    <h1 class="newsreel">Newsreel</h1>
    <p class="red-text accent-3 newsreel-sub"><i>Your Network News</i></p>
    <div class="row news-row fill-height">
    {% for article in articles %}
      <div class="xtra-margin card-panel hoverable left col s12 m5 offset-m1 l3 offset-l1">
        <p><a href="{% url 'login_register:profile' id=article.creator.id %}">{{ article.creator.first_name }}</a> shared:</p>
        {% if not request.user|already_follow:article.creator.id %}
        <p>Want to follow <a href="{% url 'login_register:follow' id=article.creator.id %}">{{ article.creator.first_name }}</a>?</p>
        {% endif %}
        <a href="{{ article.url }}"><img class="responsive-img" src="{{ article.main_image }}" /></a>
        <h5><a class="modal-trigger" href="#modal{{article.id}}">{{ article.title }}</a></h5>
        <p class="truncate">{{ article.summarized_text }}</p>
        <p>{{ article.published_on }}</p>
        {% for category in article.category_set.all %}
        <p>{{ category.name }}</p>
        <h6 class="like_count">{{ article.like_set.count }} Likes</h6>
        <div id="modal{{article.id}}" class="modal">
          <div class="modal-content">
            <h4>{{ article.title }}</h4>
            <p>{{ article.summarized_text }}</p>
          </div>
          <div class="modal-footer">
            <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
          </div>
        </div>
        <!-- <a class="test_like" a-id="{{ article.id }}" href="">Like</a> -->
        {% if not article|already_liked:request.user.id %}
        <p><a class="like_article" a-id="{{article.id}}" href="">Like</a></p>
        {% else %}
        <p><a class="unlike_article" a-id="{{article.id}}" href="">Unlike</a></p>
        {% endif %}
        {% endfor %}
      </div>
    {% endfor %}
    </div>
{% endblock %}