KickerIO/urls.py
from django.conf.urls import url, include
from django.views.decorators.csrf import csrf_exempt

print "MAIN URLS FILE"

urlpatterns = [
    url(r'^', include('apps.login_register.urls', namespace="login_register")),
    url(r'^news/', include('apps.news.urls', namespace="news")),
    url(r'^', include('django_alexa.urls')),
]

apps/login_register/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register/$', views.register, name="register"),
    url(r'^process_login/$', views.process_login, name="process_login"),
    url(r'^process_registration/$', views.process_registration, name="process_registration"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^account/(?P<id>\d+)$', views.account, name="account_settings"),
    url(r'^account/edit/(?P<id>\d+)$', views.edit, name="edit"),
    url(r'^account/update/(?P<id>\d+)$', views.update_account, name="update_account"),
    url(r'^follow/(?P<id>\d+)$', views.follow, name="follow"),
    url(r'^profile/(?P<id>\d+)$', views.profile, name="profile"),
    url(r'^search/$', views.search, name="search"),
]

apps/news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^get_new_articles/$', views.get_new_articles, name="get_new_articles"),
    url(r'^newsreel/$', views.newsreel, name="newsreel"),
    url(r'^share/(?P<id>\d+)$', views.share, name="share"),
    url(r'^like_article/(?P<id>\d+)$', views.like_article, name="like_article"),
    url(r'^unlike/(?P<id>\d+)$', views.unlike, name="unlike"),
]

apps/login_register/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

#Extend User model to add more fields
#Make a one-to-one relationship with User and add any additional fields
#If self join/one-to-one relationship doesn't work for friends feature, try proxy model
#Proxy Model link: https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField('self', blank=True, symmetrical=False)
    birthday = models.DateTimeField()
    bio = models.TextField(max_length=1000)

apps/news/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
# IDEA: Look into url shorteners. Bit.ly?
class Article(models.Model):
    title = models.CharField(max_length=255)
    summarized_text = models.TextField()
    url = models.URLField()
    published_on = models.DateTimeField()
    main_image = models.URLField()
    creator = models.ForeignKey(User, related_name="creator", default=0)
    users = models.ManyToManyField(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Category(models.Model):
    name = models.CharField(max_length=45)
    articles = models.ManyToManyField(Article)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Like(models.Model):
    user = models.ForeignKey(User)
    article = models.ForeignKey(Article)
    created_at = models.DateTimeField(auto_now_add=True)

apps/login_register/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=45, required=True)
    last_name = forms.CharField(max_length=45, required=True)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user

#Already have the bio and birthday fields defined in models.py, no need to add here
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'birthday')

    def save(self, commit=True, on_register=False, user_obj=None):
        profile = super(ProfileForm, self).save(commit=False)
        if on_register and user_obj:
            profile.user = user_obj
        profile.bio = self.cleaned_data['bio']
        profile.birthday = self.cleaned_data['birthday']
        if commit:
            profile.save()
        return profile

apps/login_register/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib import auth
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.db.models import Count
import json

from .forms import UserCreateForm, ProfileForm
from .models import Profile

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

# Create your views here.
def index(request):
    #if logged in, go to news:index
    if request.user.is_authenticated():
        return redirect(reverse('news:index'))
    form = AuthenticationForm
    context = {
        'authform': form
    }
    return render(request, 'login_register/login.html', context)

def process_login(request):
    if request.method == "POST":
        bound_form = AuthenticationForm(request.POST)
        testuser = authenticate(username=request.POST['username'], password=request.POST['password'])
        if testuser:
            login(request, testuser)
            return redirect(reverse("news:index"))
        else:
            return redirect(reverse("login_register:index"))

    return redirect(reverse("news:index"))

def register(request):
    user_form = UserCreateForm
    profile_form = ProfileForm
    context = {
        'register_form': user_form,
        'profile_form': profile_form
    }
    return render(request, 'login_register/register.html', context)

def process_registration(request):
    user_form = UserCreateForm(request.POST)
    profile_form = ProfileForm(request.POST)
    print "*"*50
    print request.POST['bio']
    print request.POST['birthday']
    print "*"*50
    if user_form.is_valid() and profile_form.is_valid():
        print "BOTH FORMS VALID!!!!"
        user = user_form.save(commit=False) #in case we want to do something else with the user object before committing...
        user.save()
        print "SAVED USER"
        profile = profile_form.save(commit=False, on_register=True, user_obj=user)
        profile.save()
        print profile
        print "SAVED PROFILE"
        login(request, user)
        print "GOING TO NEWS INDEX"
        return redirect(reverse('news:index'))
    else:
        print "Back to register..."
        return redirect(reverse('login_register:register'))

def logout(request):
    auth.logout(request)
    return redirect(reverse("login_register:index"))

def account(request, id):
    if request.user.id == int(id):
        profile = Profile.objects.get(user_id=request.user.id)
        follows = profile.follows.all()
        context = {
            'follows': follows
        }
        return render(request, 'login_register/account.html', context)
    else:
        return redirect(reverse('login_register:index'))

def edit(request, id):
    if request.user.id == int(id):
        user = User.objects.get(id=request.user.id)

        #use initial parameter to initialize preset values for form
        user_form = UserCreateForm(
            initial={
                'first_name': user.first_name,
                'last_name': user.last_name,
                'username': user.username,
                'email': user.email
            }
        )
        profile_form = ProfileForm(
            initial={
                'bio': user.profile.bio,
                'birthday': user.profile.birthday
            }
        )
        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }
        return render(request, 'login_register/edit.html', context)
    else:
        return redirect(reverse('login_register:index'))

def update_account(request, id):
    if request.method == "POST":
        bound_user = UserCreateForm(request.POST)
        bound_profile = ProfileForm(request.POST)
        print bound_user['first_name'].value()

        user = User.objects.get(id=request.user.id)
        profile = Profile.objects.get(user=user)

        user.first_name = bound_user['first_name'].value()
        user.last_name = bound_user['last_name'].value()
        user.username = bound_user['username'].value()
        user.email = bound_user['email'].value()
        profile.bio = bound_profile['bio'].value()
        profile.birthday = bound_profile['birthday'].value()
        user.save()
        profile.save()
        return redirect(reverse("login_register:account_settings", args=(request.user.id,)))

    return redirect(reverse('login_register:edit', args=(request.user.id,)))

def follow(request, id):
    #Go through the profile to set the M2M relationship
    profile = User.objects.get(id=request.user.id).profile
    profile_to_follow = User.objects.get(id=id).profile
    profile.follows.add(profile_to_follow)
    return redirect(reverse('news:newsreel'))

def profile(request, id):
    user = User.objects.get(id=id)
    recent_articles = user.article_set.all().order_by("-created_at")[:3]
    popular_articles = user.article_set.all().annotate(num_likes=Count('like')).order_by("-num_likes")[:3]
    followers = Profile.objects.filter(follows=user.profile.id).count()
    context = {
        'user': user,
        'recent_articles': recent_articles,
        'popular_articles': popular_articles,
        'followers': followers
    }
    return render(request, 'login_register/profile.html', context)

def search(request):
    users = User.objects.filter(first_name__icontains=request.POST['find_friends'])
    response_data = {}
    search_results = {}
    for user in users:
        search_results[user.username] = [user.profile.id, user.first_name, user.last_name]
    # request.session['search_results'] = search_results
    response_data['search_results'] = search_results

    return HttpResponse(
        json.dumps(response_data),
        content_type="application/json"
    )
    # return redirect(reverse("news:newsreel"))

apps/login_register/templates/login_register/account.html
{% extends 'login_register/layout.html' %}

{% block content %}
<a class="btn-flat" href="{% url 'login_register:logout' %}">Logout</a>
<a class="btn-flat" href="{% url 'news:newsreel' %}">Newsreel</a>
<a class="btn-flat" href="{% url 'login_register:account_settings' id=request.user.id %}">Account Settings</a>
<a class="btn-flat" href="{% url 'login_register:profile' id=request.user.id %}">Profile</a>

<h3 class="newsreel">{{ request.user.first_name }}'s Account</h3>
<hr>
<br>
<p>First Name: {{ request.user.first_name }}</p>
<p>Last Name: {{ request.user.last_name }}</p>
<p>Email: {{ request.user.email }}</p>
<p>Bio: {{ request.user.profile.bio }}</p>
<p>Date Joined: {{ request.user.date_joined }}</p>
<p>Birthday: {{ request.user.profile.birthday }}</p>
<h3>I am following:</h3>
{% for follow in follows %}
  <p>{{ follow.user.username }}</p>
{% endfor %}
<hr>
<a class="btn-flat" href="{% url 'login_register:edit' id=request.user.id %}">Edit</a>
{% endblock %}

apps/login_register/templates/login_register/edit.html
{% extends 'login_register/layout.html' %}

{% block content %}
    <h1 class="newsreel">Edit {{ request.user.first_name }}'s Account</h1>
    <!-- using <formname>.<fieldname> allows access to each individual field for rendering -->
    <form action="{% url 'login_register:update_account' id=request.user.id %}" method="POST">
      {% csrf_token %}
      <p>First Name: {{ user_form.first_name }}</p>
      <p>Last Name: {{ user_form.last_name }}</p>
      <p>Username: {{ user_form.username }}</p>
      <p>Email: {{ user_form.email }}</p>
      {{ profile_form.as_p }}
      <input class="btn-flat" type="submit" value="Update Account">
    </form>
    <br>
    <a class="btn-flat" href="{% url 'login_register:account_settings' id=request.user.id %}">Back to Profile</a>
{% endblock %}

apps/login_register/templates/login_register/layout.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>KickerIO</title>
    <link rel="stylesheet" type="text/css" href="{% static 'login_register/css/materialize.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'login_register/css/landing.css' %}" />
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'login_register/js/materialize.js' %}"></script>
    <script src="{% static 'login_register/js/masonry.js' %}"></script>
    <script src="{% static 'login_register/js/scripts.js' %}"></script>
  </head>
  <body class="colorful">
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
  </body>
</html>

apps/login_register/templates/login_register/login.html
{% extends 'login_register/layout.html' %}
{% load static %}

{% block content %}

<h1 class="title-text flow-text">Kicker.io</h1>
<h5 class="title-subtext flow-text">Breaking news made social</h5>
<img class="responsive-img cover-img" src="{% static 'login_register/img/cover2.jpg' %}" alt="Newspaper and Coffee" />
<form action="{% url 'login_register:process_login' %}" method="POST">
  {% csrf_token %}
  <div class="input-field">
    <label for="{{ authform.username.id_for_label }}">Username</label>
    {{ authform.username }}
  </div>
  <div class="input-field">
    <label for="{{ authform.password.id_for_label }}">Password</label>
    {{ authform.password }}
  </div>
  <input class="btn-flat" type="submit" value="Login">
</form>
<a class="btn-flat" href="{% url 'login_register:register' %}">Not a member yet? Sign up now!</a>

{% endblock %}

apps/login_register/templates/login_register/profile.html
{% extends 'login_register/layout.html' %}
{% load profile_follow_extras %}

{% block content %}
<a class="btn-flat" href="{% url 'login_register:logout' %}">Logout</a>
<a class="btn-flat" href="{% url 'news:newsreel' %}">Newsreel</a>
<a class="btn-flat" href="{% url 'login_register:account_settings' id=request.user.id %}">Account Settings</a>
    <h1 class="newsreel">{{ user.first_name }}'s Profile</h1>
    {% if not request.user|profile_already_follow:user.id %}
    <form action="{% url 'login_register:follow' id=user.id %}">
      {% csrf_token %}
      <input class="btn" type="submit" value="Follow">
    </form>
    {% elif request.user.id != user.id %}
    <p class="red-text accent-3">Following!</p>
    {% endif %}
    <p>{{ followers }} follower(s)</p>
    <div class="carousel">
      {% for article in popular_articles %}
      <a class="carousel-item" href="{{ article.url }}"><img src="{{ article.main_image }}"></a>
      {% endfor %}
    </div>
    <h3 class="newsreel">Recent Articles</h3>

    <ul class="collapsible popout" data-collapsible="accordion">
      {% for article in recent_articles %}
        <li>
          <div class="collapsible-header">{{ article.title }} - {{ article.created_at }}</div>
          <div class="collapsible-body">{{ article.summarized_text }}</div>
        </li>
      {% endfor %}
    </ul>

    <h3 class="newsreel">Popular Articles</h3>

    <ul class="collapsible popout" data-collapsible="accordion">
      {% for article in popular_articles %}
        <li>
          <div class="collapsible-header">{{ article.title }} - {{ article.like_set.count }} Likes</div>
          <div class="collapsible-body">{{ article.summarized_text }}</div>
        </li>
      {% endfor %}
    </ul>

{% endblock %}

apps/login_register/templates/login_register/register.html
{% extends 'login_register/layout.html' %}

{% block content %}

<h1 class="newsreel">Register</h1>
<form action="{% url 'login_register:process_registration' %}" method="POST">
  {% csrf_token %}
  {{ register_form.as_p }}
  {{ profile_form.as_p }}
  <input class="btn-flat" type="submit" value="Register">
</form>
<br>
<a class="btn-flat" href="{% url 'login_register:index' %}">Already a member? Log in!</a>

{% endblock %}